### ISSUE TITLE
Just a random issue about love...

### ISSUE THREAD

**Issue by terence-tarrega** [gb8462/BSIT_Cafe_Collab#19]
Love is **War** 
Love is **Torture** 
Love is an **Experience**
Love is **A Moment in Time** where you and another person feels happy being in each other's company

Love hurts, **A LOT** especially if one cannot attain it. But nevertheless one will overcome this and move on eventually...
Loving, is not easy y'know.

I think I'm gonna write about this in my notes hahah... Maybe even try and post my experience in Wattpad like Azi? hahah
Gomen, I'm just having fun doing this here hahah :3

**Comment by terence-tarrega** [comment]
I love this feature hahaha... pun intended

**Comment by gb8462** [comment]
“I have spent all my life resisting the desire to end it. I do this because I must, because I love life. This is what it means to love: to persist, despite everything.”
(The Diaries of Franz Kafka)

**Comment by gb8462** [comment]
“You can hold yourself back from the sufferings of the world; that is something you are free to do, and it accords with your nature. But perhaps precisely this holding back is the one suffering you could avoid.”
(Franz Kafka Letters to Friends, Family, and Editors)

**Comment by gb8462** [comment]
“The meaning of life is that it stops.”

**Comment by gb8462** [comment]
“I want to live. I want to see what happens in life, even if it’s painful. I want to experience it, until the very end.”
